### ISSUE TITLE
 firebeetle v2 esp32-e upload issue

### ISSUE THREAD

**Issue by Dozentz** [lmarzen/esp32-weather-epd#3] opened 2022-12-20 20:00 UTC
Will work from usb? I have a constantly blinking red battery light and a white screen

**Comment by lmarzen** [comment] 2022-12-20 20:03
Yes it will work over usb.If pressing the reset button doesn't cause the display to do anything then it may be wired incorrectly?

**Comment by Dozentz** [comment] 2022-12-20 20:13
Connected as picture
![5MqU0-DA](https://user-images.githubusercontent.com/10892971/208757844-3d953e2d-690a-4c3d-b146-e1bcd635ed3f.jpeg)
![ThvfcyEo](https://user-images.githubusercontent.com/10892971/208757852-7aef20b5-41a9-4e6f-b98e-21f6fe713508.jpeg)

**Comment by lmarzen** [comment] 2022-12-20 21:14
The switches on the e-paper hat. "Interface Config: Set switch to position 1."

**Comment by lmarzen** [comment] 2022-12-20 21:36
You could also try disconnecting it from usb power and then reconnecting it. Sometimes the esp32s can be finicky after you upload your code.

**Comment by Dozentz** [comment] 2022-12-20 22:27
I turned off the power and turned it on again, set the flag to 1. Tell me what else can be done?

**Comment by lmarzen** [comment] 2022-12-20 23:30
Are you sure the code was successfully uploaded to the esp32?

**Comment by lmarzen** [comment] 2022-12-20 23:31
I'm running out of ideas; maybe a try to disconnect and reconnect the connectors?

**Comment by Dozentz** [comment] 2022-12-21 05:50
upload complete ?
![sucsees](https://user-images.githubusercontent.com/10892971/208831291-7dd3450b-b9ba-4028-81ef-e98732832516.jpg)

**Comment by lmarzen** [comment] 2022-12-21 05:51
yup, that looks good:/

**Comment by lmarzen** [comment] 2022-12-21 14:54
open the serial monitor while the esp32 is connected via usb. It will print debug debug messages that indicate what it is doing.

**Comment by Dozentz** [comment] 2022-12-21 16:51
Tell me how to do it?

**Comment by lmarzen** [comment] 2022-12-21 17:01
in vscode at the bottom(near upload and build buttons) there should be a button to open the serial monitor. Hover over the buttons to find it. Once you find and click it, press the reset button on the esp32, then the esp32 should print out some debug messages that i put in the code to indicate what it is doing. If the esp32 is hanging somewhere this should give me enough information to figure out what might be causing it.

**Comment by Dozentz** [comment] 2022-12-21 17:06
debug
![esp32](https://user-images.githubusercontent.com/10892971/208963027-c73bca6f-74fa-42a1-92d5-3becd78657a3.jpg)
![esp32-1](https://user-images.githubusercontent.com/10892971/208963070-d4d43676-f351-44bd-93cc-5e9668734c8f.jpg)

**Comment by lmarzen** [comment] 2022-12-21 17:17
Oh weird, looks to be having a boot error before it is executing any of my code. I can look into this, but I am traveling for the holidays and wont be able to try to recreate the issue until mid next month.

**Comment by Dozentz** [comment] 2023-01-16 09:41
Good afternoon. Were you able to fix the error?

**Comment by lmarzen** [comment] 2023-01-16 18:45
I forgot about this over holiday, I have some time today to work on it. I will keep you updated.

**Comment by lmarzen** [comment] 2023-01-16 18:47
I am able to recreate the issue you were describing simply by uploading my existing known good project. Some configuration thing must have changed. hmmmmm

**Comment by lmarzen** [comment] 2023-01-16 18:53
I found another group of people with the same issue. https://github.com/esphome/issues/issues/3921

**Comment by lmarzen** [comment] 2023-01-16 19:14
So I guess the issue is that the firebeetle v2 that I used for this project only has 4MB of flash, while other versions of the esp32 have more flash. I have no idea why it was working before if this is the issue. Sounds like some upload tool got smarter and that the firebeetle v2 might also not have proper support. I have no idea what has happened, I guess I will change my controller out for the older firebeetle that has 16MB of flash and micro usb.

**Comment by Dozentz** [comment] 2023-01-16 19:57
My controller version is type С. How can I find out how much flash memory is in my version?

**Comment by lmarzen** [comment] 2023-01-16 19:59
https://www.dfrobot.com/product-2195.html vs https://www.dfrobot.com/product-1590.html

**Comment by lmarzen** [comment] 2023-01-16 19:59
The usb C version is only 4MB. Somehow this never caused an issue until now, even though the compiled code is like 11MB.

**Comment by Dozentz** [comment] 2023-01-16 20:04
I understand the problem is now with the compiler

**Comment by lmarzen** [comment] 2023-01-16 20:10
No my understanding is that this board is properly supported in platformio and that when I originally created this project for some reason I was able to upload a bigger binary to the controller without it freaking out, but now there is some extra check or maybe even just a change in environment that is causing this issues. I have no idea why this worked in the first place with a 4MB flash. Clearly 11MB > 4MB. I must have over looked that the newer usb c firebeetle had less flash than its predecessor. So the solution is that you must buy the micro usb firebeetle because that has 16mb of flash. I am testing it now because I have the hardware on hand.

**Comment by lmarzen** [comment] 2023-01-16 21:53
Okay, I have dug more into it. It seems to be a support issue with platformio. Maybe not flash size issue?

**Comment by Dozentz** [comment] 2023-01-16 22:09
Need to ask on the forum https://community.platformio.org.

**Comment by lmarzen** [comment] 2023-01-16 22:09
Alright, forget my earlier explanation. I think I got it now. So the Firebeetle v2 esp32-e is not official supported but it worked earlier last year. So the solution is to use an older version of expressif32, So in platform.ini try change `platform = espressif32` to `platform = espressif32@5.0.0`

**Comment by lmarzen** [comment] 2023-01-16 22:19
https://github.com/platformio/platform-espressif32/issues/644

**Comment by lmarzen** [comment] 2023-01-17 03:02
Alright. Fingers crossed, the issue should be fixed now. Let me know how it goes.

**Comment by Dozentz** [comment] 2023-01-17 20:11
Ok

**Comment by Dozentz** [comment] 2023-01-18 16:26
Everything worked. Great job. Tell me how to make a weather icon shadow with curves and a battery with 4 compartments. Thanks to)
![gitub](https://user-images.githubusercontent.com/10892971/213235580-f1384d93-08f0-4c55-910a-4353a3ae5ec7.jpg)

**Closed** 2023-01-18 18:21 UTC

**Comment by lmarzen** [comment] 2023-01-18 18:37
I created a new issue with instructions for changing icons. https://github.com/lmarzen/esp32-weather-epd/issues/4
